### ISSUE TITLE
Allow restricting "lineCommentStyle" match to the beginning of a line.

### ISSUE THREAD

**Issue by jgerigmeyer** [FWeinb/CDocParser#16]
As its written now, any occurrence of the `lineCommentStyle` will be matched and stripped from the parsed return value. This makes it impossible to "comment a comment", or use the `lineCommentStyle` string within a comment. For example, using SassDoc, it would be nice to be able to have the comment syntax within a comment (to show how to make a comment):

```scss
/// Here is how to add a comment:
/// /// I am a comment
```

Right now, the regex matches every occurrence of `///`, resulting in `lines`:

```
['Here is how to add a comment:', 'I am a comment']
```

Instead of what I'd like:

```
['Here is how to add a comment:', '/// I am a comment']
```

One "fix" would be enforcing that comments must begin with a newline by changing the regex in [`index.js#L80`](https://github.com/FWeinb/CDocParser/blob/master/index.js#L80) from:

```js
new RegExp(escapeStringRegexp(lineCommentStyle) + '[\\/]*');
```

to:

```js
new RegExp('(^|\n)' + escapeStringRegexp(lineCommentStyle) + '[\\/]*');
```

I'm not sure if that would break other use-cases (it doesn't break anything else in my SassDoc project, at least)... Perhaps it could be an option turned on or off?

Or even better, is there a way to mark a section of text as "escaped" such that it won't be stripped by CDocParser, or enforce only one comment per line?

**Comment by jgerigmeyer** [comment]
I submitted a PR (#17) which addresses this without breaking other use-cases. If two or more instances of `lineCommentStyle` occur on the same line, it does not try to interpret any of them as comments after the first instance.

**Comment by pascalduez** [comment]
Hi,

it feels reasonable to only allow one doc comment per line, at least in the SassDoc context.

As for this PR I hope @FWeinb will be able to have a look at it.
Otherwise we might have to fork CDocParser to the SassDoc organisation and start using it...

**Comment by FWeinb** [comment]
Sorry for not responding earlier. I added @pascalduez as a maintainer to cdocparser. I would be glad if you could merge the PR.

**Comment by jgerigmeyer** [comment]
@pascalduez Anything holding up merging the PR, etc? Thanks!

**Comment by pascalduez** [comment]
@FWeinb Do I have publish rights on npm as well? ;)

**Comment by FWeinb** [comment]
@pascalduez Sorry for that. Just added you.

**Comment by pascalduez** [comment]
@jgerigmeyer `cdocparser@0.15.0` published.

I will need to run some tests before bumping the dependency in `scss-comment-parser`, there was a `0.14.0` version which we haven't yet finished integrating, and I'm wondering if there's some breakages. See https://github.com/SassDoc/sassdoc/pull/410

**Comment by jgerigmeyer** [comment]
@pascalduez What breakages are you seeing? There's a failed build on that PR merge (https://travis-ci.org/SassDoc/sassdoc/builds/90808006), but it looks like it's a simple linting error. Is there something else I'm missing?

**Comment by pascalduez** [comment]
@jgerigmeyer That branch was never merged into master, and I don't want to rush releasing this, it would need proper docs etc.

**Comment by jgerigmeyer** [comment]
@pascalduez That makes sense... though I'll point out that since scss-comment-parser is requiring `"cdocparser": "^0.13.0"`, most people will already be getting `v0.14.0` (and now `v0.15.0`), automatically, and have been for awhile. https://github.com/SassDoc/scss-comment-parser/blob/master/package.json#L17

**Comment by pascalduez** [comment]
@jgerigmeyer I though `0.*.*` based semver ranges does not behave the same and as such should stick to `0.13`. Testing...

**Comment by jgerigmeyer** [comment]
@pascalduez Oh, you're correct. My mistake! (I've been using `v0.14.0` -- and now `v0.15.0` without issue, for what it's worth.)
